<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/06/26 07:41:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=sunhrm_jan',
  'username' => 'root',
  'password' => NULL,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
