<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/06/26 11:37:29
sfConfig::add(array(
  'mod_recruitmentapply_enabled' => true,
  'mod_recruitmentapply_view_class' => 'sfPHP',
));
