<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/06/26 11:55:40
sfConfig::add(array(
  'mod_performancetracker_enabled' => true,
  'mod_performancetracker_view_class' => 'sfPHP',
));
